 name: 🐍 Snake animation

on:
  schedule:
    - cron: "0 0 * * *"  # Gera diariamente
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a cobra (contribuições)
        uses: Platane/snk@v3
        with:
          github_user_name: SERUMANINH0
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
